import authorImg1 from "../../assets/images/publishers/publisher.png";

export const publications = [
    {
      boothNumber: 1,
      imgURL: authorImg1,
      name: "Publisher One",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 2,
      imgURL: authorImg1,
      name: "Publisher Two",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 3,
      imgURL: authorImg1,
      name: "Publisher Three",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 4,
      imgURL: authorImg1,
      name: "Publisher Four",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 5,
      imgURL: authorImg1,
      name: "Publisher Five",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 6,
      imgURL: authorImg1,
      name: "Publisher Six",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 7,
      imgURL: authorImg1,
      name: "Publisher Seven",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 8,
      imgURL: authorImg1,
      name: "Publisher Eight",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 9,
      imgURL: authorImg1,
      name: "Publisher Nine",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 10,
      imgURL: authorImg1,
      name: "Publisher Ten",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 11,
      imgURL: authorImg1,
      name: "Publisher Eleven",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
    {
      boothNumber: 12,
      imgURL: authorImg1,
      name: "Publisher Twelve",
      link: "/publishers",
      books: ["Book A1", "Book A2", "Book A3"],
    },
  ];